// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVuTTL7Qpg8VJTEdneltERyhVl-PNCoeU',
    appId: '1:503863571338:web:2013a49500d71fd70d0e73',
    messagingSenderId: '503863571338',
    projectId: 'stellar-aleph-365809',
    authDomain: 'stellar-aleph-365809.firebaseapp.com',
    storageBucket: 'stellar-aleph-365809.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGSX_7cSRQIYZZto3g6rJK9rKRra_7jk',
    appId: '1:503863571338:android:f5004cc01344b3e30d0e73',
    messagingSenderId: '503863571338',
    projectId: 'stellar-aleph-365809',
    storageBucket: 'stellar-aleph-365809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbDH-2EH2k5CLLkVFH6j34GwkvOaBYhAE',
    appId: '1:503863571338:ios:7ededb0ce53bf4290d0e73',
    messagingSenderId: '503863571338',
    projectId: 'stellar-aleph-365809',
    storageBucket: 'stellar-aleph-365809.appspot.com',
    iosClientId: '503863571338-1es9ge6q96avkr0re8a0lvdbbgc761p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapppradeep.newApp',
  );
}
